services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
